### PR TITLE
[DEV-7473] Allow utf in filenames

### PR DESCRIPTION
**Pull request by alexgt9**
Issue: https://signaturit.atlassian.net/browse/SUP-3631

### CODE REVIEW

**Comment by alexgt9** [comment]
@ecentinela How should we publish this new version?

**Comment by ecentinela** [comment]
In this other repo https://github.com/signaturit/net-sdk-dev you have the instructions to publish a new version.

Is a bit complicated because you need to setup a windows virtual machine in order to install Nuget Package Explorer...

**Comment by alexgt9** [comment]
> In this other repo https://github.com/signaturit/net-sdk-dev you have the instructions to publish a new version.
> 
> Is a bit complicated because you need to setup a windows virtual machine in order to install Nuget Package Explorer...

I think that now we can do it using the cli in mac https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli 🍀

**Comment by ecentinela** [comment]
That would be great! Let me know if it works! 👌

**Pull request closed without merging**
